### ISSUE TITLE
Need way to configure API url

### ISSUE THREAD

**Issue by Spencatro** [gitsubmit/gitsubmit.github.io#2]
So that tests can run on a pure staging environment (i.e. serve web pages from some webserver, connect to a local version of the API, click and do stuff, etc)

**Comment by sonph** [comment]
As I understand it we need a way to configure the API URL depending on the environments such as for example `localhost:8000` for staging/testing and `api.gitsubmit.com` for production?

**Comment by Spencatro** [comment]
Yes, exactly. I want to be able to start a feature/development version of the API, and then test it against a feature/development version of the frontend code (and also maybe even mix and match between master versions of each). Though I am not sure what the best method of doing this would be. (Maybe a `/?use_api=http://localhost:5555` or something?)

**Comment by sonph** [comment]
I can throw in a `config.js` file and you can append a custom variable to the file like this??

```
echo "var API_URL = 'http://localhost:5555/'" >> config.js
```

Then we'll check if `API_URL` is defined? yes -> use it; no -> use default url

**Comment by Spencatro** [comment]
That seems reasonable to me
